import { describe, it, expect, beforeAll, afterAll } from "vitest";
import * as XLSX from "xlsx";
import { getTrackingStartDate, setTrackingStartDate } from "@domain/value-objects/trackingWindow";
import { isStesWorkbookFile, parseStesWorkbook, STES_SCHEMA_NAME } from "./StesWorkbookParser";

type Cell = string | number | Date | null;

const OBS_HEADERS = [
  "Observation ID",
  "Document ID",
  "Transaction Type",
  "Ticker",
  "Company Name",
  "ISIN",
  "Exchange",
  "Trade Date",
  "Trade Time",
  "Quantity",
  "Price",
  "Gross Amount",
  "Fees",
  "Taxes",
  "Net Amount",
  "Dividend Amount",
  "Dividend Per Share",
  "Currency",
  "Order Type",
  "Source Page",
  "Transaction Reference",
  "Order Number",
  "Execution Number",
  "Extraction Confidence",
  "Extraction Notes",
];

const DOC_HEADERS = [
  "Document ID",
  "File Name",
  "Document Type",
  "Broker Name",
  "Broker Account",
  "Statement Date",
  "Document Date",
  "Page Count",
  "Extraction Method",
  "Document Notes",
];

interface ObsInput {
  id?: string;
  doc?: string;
  type?: string;
  ticker?: Cell;
  companyName?: string;
  date?: Cell;
  time?: Cell;
  quantity?: Cell;
  price?: Cell;
  gross?: Cell;
  fees?: Cell;
  taxes?: Cell;
  dividendAmount?: Cell;
  currency?: string;
  transactionReference?: string;
  confidence?: string;
  notes?: string;
}

function obsRow(o: ObsInput): Cell[] {
  return [
    o.id ?? null,
    o.doc ?? null,
    o.type ?? null,
    o.ticker ?? null,
    o.companyName ?? null,
    null,
    null,
    o.date ?? null,
    o.time ?? null,
    o.quantity ?? null,
    o.price ?? null,
    o.gross ?? null,
    o.fees ?? null,
    o.taxes ?? null,
    null,
    o.dividendAmount ?? null,
    null,
    o.currency ?? null,
    null,
    null,
    o.transactionReference ?? null,
    null,
    null,
    o.confidence ?? null,
    o.notes ?? null,
  ];
}

function buildWorkbook(options: {
  schemaName?: string | null;
  schemaVersion?: string | null;
  documents?: Cell[][];
  observations?: Cell[][];
  omitSheets?: string[];
}): ArrayBuffer {
  const wb = XLSX.utils.book_new();
  const omit = new Set(options.omitSheets ?? []);
  if (!omit.has("Metadata")) {
    const metadata: Cell[][] = [
      ["Key", "Value"],
      ...(options.schemaName === null ? [] : [["Schema Name", options.schemaName ?? STES_SCHEMA_NAME] as Cell[]]),
      ...(options.schemaVersion === null ? [] : [["Schema Version", options.schemaVersion ?? "1.1"] as Cell[]]),
      ["Generated By", "test"],
    ];
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(metadata), "Metadata");
  }
  if (!omit.has("Documents")) {
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([DOC_HEADERS, ...(options.documents ?? [])]), "Documents");
  }
  if (!omit.has("Observations")) {
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([OBS_HEADERS, ...(options.observations ?? [])]), "Observations");
  }
  return XLSX.write(wb, { type: "array", bookType: "xlsx" }) as ArrayBuffer;
}

const doc = (id: string, type: string, fileName = `${id}.pdf`): Cell[] => [id, fileName, type, "Thndr", null, null, null, 1, "NATIVE_TEXT", null];

let originalTrackingStart: string;
beforeAll(() => {
  originalTrackingStart = getTrackingStartDate();
  setTrackingStartDate("2026-01-01");
});
afterAll(() => setTrackingStartDate(originalTrackingStart));

describe("isStesWorkbookFile", () => {
  it("recognizes .xlsx by extension and by content type", () => {
    expect(isStesWorkbookFile({ name: "export.XLSX", type: "" })).toBe(true);
    expect(isStesWorkbookFile({ name: "blob", type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" })).toBe(true);
    expect(isStesWorkbookFile({ name: "statement.pdf", type: "application/pdf" })).toBe(false);
    expect(isStesWorkbookFile({ name: "export.csv", type: "text/csv" })).toBe(false);
  });
});

describe("parseStesWorkbook — valid workbooks", () => {
  it("maps BUY/SELL observations to candidates and DIVIDEND observations to dividends", async () => {
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "STATEMENT"), doc("DOC-02", "INVOICE"), doc("DOC-03", "SCREENSHOT", "IMG.png")],
      observations: [
        obsRow({
          id: "OBS-0001",
          doc: "DOC-02",
          type: "BUY",
          ticker: "COMI",
          companyName: "Commercial International Bank",
          date: "2026-03-02",
          time: "11:42",
          quantity: 100,
          price: 82.5,
          fees: 12.38,
          taxes: 4.13,
          transactionReference: "88213",
          confidence: "HIGH",
        }),
        obsRow({ id: "OBS-0002", doc: "DOC-01", type: "SELL", ticker: "EAST", date: "2026-04-10", quantity: 80, price: 27.3 }),
        obsRow({ id: "OBS-0003", doc: "DOC-03", type: "DIVIDEND", ticker: "EAST", date: "2026-03-20", dividendAmount: 340 }),
      ],
    });

    const result = await parseStesWorkbook(buffer);
    expect(result.ok).toBe(true);
    expect(result.warnings).toEqual([]);
    expect(result.documentCount).toBe(3);
    expect(result.observationCount).toBe(3);

    expect(result.candidates).toHaveLength(2);
    expect(result.candidates[0]).toMatchObject({
      ticker: "COMI",
      companyName: "Commercial International Bank",
      side: "BUY",
      shares: 100,
      price: 82.5,
      fees: 12.38,
      taxes: 4.13,
      date: "2026-03-02",
      time: "11:42",
      confidence: "high",
      source: "invoice",
      transactionNumber: "88213",
    });
    // Blank cells mean UNKNOWN, never zero — and blank confidence defaults to medium.
    expect(result.candidates[1]).toMatchObject({ ticker: "EAST", side: "SELL", shares: 80, price: 27.3, source: "statement", confidence: "medium" });
    expect(result.candidates[1].fees).toBeUndefined();
    expect(result.candidates[1].taxes).toBeUndefined();
    expect(result.candidates[1].time).toBeUndefined();

    expect(result.dividends).toEqual([
      { ticker: "EAST", companyName: undefined, date: "2026-03-20", amount: 340, source: "screenshot" },
    ]);
  });

  it("keeps two observations of the same execution from two documents as two candidates — zero dedup at the evidence layer", async () => {
    const shared = { type: "BUY", ticker: "COMI", date: "2026-03-02", quantity: 100, price: 82.5 } as const;
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "STATEMENT"), doc("DOC-02", "INVOICE")],
      observations: [obsRow({ id: "OBS-0001", doc: "DOC-01", ...shared }), obsRow({ id: "OBS-0002", doc: "DOC-02", ...shared })],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.candidates).toHaveLength(2);
    expect(result.candidates.map((c) => c.source)).toEqual(["statement", "invoice"]);
  });

  it("coerces real Excel date/time cells (Date objects) to ISO strings", async () => {
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "STATEMENT")],
      observations: [
        obsRow({ id: "OBS-0001", doc: "DOC-01", type: "BUY", ticker: "COMI", date: new Date(Date.UTC(2026, 2, 2)), quantity: 10, price: 5 }),
      ],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.candidates).toHaveLength(1);
    expect(result.candidates[0].date).toBe("2026-03-02");
  });

  it("maps NOTIFICATION/EMAIL/PDF document types to their honest sources (never fabricated statement authority)", async () => {
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "NOTIFICATION"), doc("DOC-02", "EMAIL"), doc("DOC-03", "PDF")],
      observations: [
        obsRow({ id: "OBS-0001", doc: "DOC-01", type: "BUY", ticker: "COMI", date: "2026-03-02", quantity: 10, price: 5 }),
        obsRow({ id: "OBS-0002", doc: "DOC-02", type: "BUY", ticker: "COMI", date: "2026-03-03", quantity: 10, price: 5 }),
        obsRow({ id: "OBS-0003", doc: "DOC-03", type: "BUY", ticker: "COMI", date: "2026-03-04", quantity: 10, price: 5 }),
      ],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.candidates.map((c) => c.source)).toEqual(["notification", "email", "other-document"]);
  });

  it("flags a Gross Amount that contradicts Quantity × Price but still imports the row for review", async () => {
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "STATEMENT")],
      observations: [
        obsRow({ id: "OBS-0001", doc: "DOC-01", type: "BUY", ticker: "COMI", date: "2026-03-02", quantity: 100, price: 82.5, gross: 9000 }),
      ],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.candidates).toHaveLength(1);
    expect(result.warnings).toHaveLength(1);
    expect(result.warnings[0]).toContain("OBS-0001");
    expect(result.warnings[0]).toContain("Gross Amount");
  });
});

describe("parseStesWorkbook — Extraction Notes: needsConfirmation", () => {
  it("flags a candidate needsConfirmation when Extraction Notes is exactly 'Needs Confirmation'", async () => {
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "ORDERS_SCREEN")],
      observations: [
        obsRow({ id: "OBS-0001", doc: "DOC-01", type: "SELL", ticker: "ABUK", date: "2026-02-26", quantity: 29, price: 41.17, notes: "Needs Confirmation" }),
      ],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.candidates).toHaveLength(1);
    expect(result.candidates[0].needsConfirmation).toBe(true);
  });

  it("is case/whitespace-insensitive", async () => {
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "ORDERS_SCREEN")],
      observations: [
        obsRow({ id: "OBS-0001", doc: "DOC-01", type: "BUY", ticker: "COMI", date: "2026-03-02", quantity: 10, price: 5, notes: "  needs confirmation  " }),
      ],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.candidates[0].needsConfirmation).toBe(true);
  });

  it("leaves needsConfirmation unset for a blank or unrelated Extraction Notes value", async () => {
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "STATEMENT")],
      observations: [
        obsRow({ id: "OBS-0001", doc: "DOC-01", type: "BUY", ticker: "COMI", date: "2026-03-02", quantity: 10, price: 5 }),
        obsRow({ id: "OBS-0002", doc: "DOC-01", type: "BUY", ticker: "COMI", date: "2026-03-03", quantity: 10, price: 5, notes: "Ticker was slightly blurry" }),
      ],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.candidates[0].needsConfirmation).toBeUndefined();
    expect(result.candidates[1].needsConfirmation).toBeUndefined();
  });
});

describe("parseStesWorkbook — file-level validation", () => {
  it("fails a workbook missing a required sheet", async () => {
    const buffer = buildWorkbook({ omitSheets: ["Documents"] });
    const result = await parseStesWorkbook(buffer);
    expect(result.ok).toBe(false);
    expect(result.warnings[0]).toContain("Documents");
  });

  it("fails a workbook that does not self-identify as STES", async () => {
    const buffer = buildWorkbook({ schemaName: "Random Spreadsheet" });
    const result = await parseStesWorkbook(buffer);
    expect(result.ok).toBe(false);
    expect(result.warnings[0]).toContain("Random Spreadsheet");
  });

  it("fails an unsupported major schema version", async () => {
    const buffer = buildWorkbook({ schemaVersion: "2.0", documents: [doc("DOC-01", "STATEMENT")] });
    const result = await parseStesWorkbook(buffer);
    expect(result.ok).toBe(false);
    expect(result.warnings[0]).toContain("2.0");
  });

  it("accepts any 1.x minor version", async () => {
    const buffer = buildWorkbook({
      schemaVersion: "1.4",
      documents: [doc("DOC-01", "STATEMENT")],
      observations: [obsRow({ id: "OBS-0001", doc: "DOC-01", type: "BUY", ticker: "COMI", date: "2026-03-02", quantity: 10, price: 5 })],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.ok).toBe(true);
    expect(result.candidates).toHaveLength(1);
  });

  it("fails a duplicate Document ID — allocation of observations to documents would be ambiguous", async () => {
    const buffer = buildWorkbook({ documents: [doc("DOC-01", "STATEMENT"), doc("DOC-01", "INVOICE")] });
    const result = await parseStesWorkbook(buffer);
    expect(result.ok).toBe(false);
    expect(result.warnings[0]).toContain('"DOC-01"');
  });

  it("fails bytes that are not a readable workbook", async () => {
    const result = await parseStesWorkbook(new TextEncoder().encode("not an xlsx").buffer as ArrayBuffer);
    expect(result.ok).toBe(false);
  });
});

describe("parseStesWorkbook — row-level validation (each bad row rejected by name, the rest still import)", () => {
  it("rejects unsupported transaction types instead of coercing them", async () => {
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "STATEMENT")],
      observations: [
        obsRow({ id: "OBS-0001", doc: "DOC-01", type: "DEPOSIT", date: "2026-03-02" }),
        obsRow({ id: "OBS-0002", doc: "DOC-01", type: "BUY", ticker: "COMI", date: "2026-03-02", quantity: 10, price: 5 }),
      ],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.ok).toBe(true);
    expect(result.candidates).toHaveLength(1);
    expect(result.warnings).toHaveLength(1);
    expect(result.warnings[0]).toContain("OBS-0001");
    expect(result.warnings[0]).toContain("DEPOSIT");
  });

  it("rejects an observation referencing an unlisted Document ID", async () => {
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "STATEMENT")],
      observations: [obsRow({ id: "OBS-0001", doc: "DOC-99", type: "BUY", ticker: "COMI", date: "2026-03-02", quantity: 10, price: 5 })],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.candidates).toHaveLength(0);
    expect(result.warnings[0]).toContain('"DOC-99"');
  });

  it("rejects a BUY with no ticker, naming the company so the user can fix the workbook", async () => {
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "STATEMENT")],
      observations: [
        obsRow({ id: "OBS-0001", doc: "DOC-01", type: "BUY", companyName: "Some Unknown Co", date: "2026-03-02", quantity: 10, price: 5 }),
      ],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.candidates).toHaveLength(0);
    expect(result.warnings[0]).toContain("Some Unknown Co");
  });

  it("rejects fractional or non-positive quantities and prices", async () => {
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "STATEMENT")],
      observations: [
        obsRow({ id: "OBS-0001", doc: "DOC-01", type: "BUY", ticker: "COMI", date: "2026-03-02", quantity: 10.5, price: 5 }),
        obsRow({ id: "OBS-0002", doc: "DOC-01", type: "BUY", ticker: "COMI", date: "2026-03-02", quantity: 10, price: 0 }),
      ],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.candidates).toHaveLength(0);
    expect(result.warnings).toHaveLength(2);
  });

  it("rejects a DIVIDEND row carrying Quantity/Price — a misclassification signal, never silently trimmed", async () => {
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "STATEMENT")],
      observations: [
        obsRow({ id: "OBS-0001", doc: "DOC-01", type: "DIVIDEND", ticker: "EAST", date: "2026-03-20", dividendAmount: 340, quantity: 100, price: 3.4 }),
      ],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.dividends).toHaveLength(0);
    expect(result.warnings[0]).toContain("misclassified");
  });

  it("rejects a BUY row carrying a Dividend Amount for the same reason", async () => {
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "STATEMENT")],
      observations: [
        obsRow({ id: "OBS-0001", doc: "DOC-01", type: "BUY", ticker: "COMI", date: "2026-03-02", quantity: 10, price: 5, dividendAmount: 50 }),
      ],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.candidates).toHaveLength(0);
    expect(result.warnings[0]).toContain("misclassified");
  });

  it("rejects non-EGP currencies per row", async () => {
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "STATEMENT")],
      observations: [
        obsRow({ id: "OBS-0001", doc: "DOC-01", type: "BUY", ticker: "COMI", date: "2026-03-02", quantity: 10, price: 5, currency: "USD" }),
      ],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.candidates).toHaveLength(0);
    expect(result.warnings[0]).toContain("USD");
  });

  it("rejects a duplicate Observation ID", async () => {
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "STATEMENT")],
      observations: [
        obsRow({ id: "OBS-0001", doc: "DOC-01", type: "BUY", ticker: "COMI", date: "2026-03-02", quantity: 10, price: 5 }),
        obsRow({ id: "OBS-0001", doc: "DOC-01", type: "BUY", ticker: "COMI", date: "2026-03-03", quantity: 10, price: 5 }),
      ],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.candidates).toHaveLength(1);
    expect(result.warnings[0]).toContain("duplicate Observation ID");
  });

  it("excludes observations outside the tracked date range, with a count", async () => {
    const buffer = buildWorkbook({
      documents: [doc("DOC-01", "STATEMENT")],
      observations: [
        obsRow({ id: "OBS-0001", doc: "DOC-01", type: "BUY", ticker: "COMI", date: "2020-06-01", quantity: 10, price: 5 }),
        obsRow({ id: "OBS-0002", doc: "DOC-01", type: "BUY", ticker: "COMI", date: "2099-01-01", quantity: 10, price: 5 }),
        obsRow({ id: "OBS-0003", doc: "DOC-01", type: "BUY", ticker: "COMI", date: "2026-03-02", quantity: 10, price: 5 }),
      ],
    });
    const result = await parseStesWorkbook(buffer);
    expect(result.candidates).toHaveLength(1);
    expect(result.warnings.some((w) => w.includes("2 observation(s)") && w.includes("tracked date range"))).toBe(true);
  });

  it("warns when the Observations sheet is empty", async () => {
    const buffer = buildWorkbook({ documents: [doc("DOC-01", "STATEMENT")] });
    const result = await parseStesWorkbook(buffer);
    expect(result.ok).toBe(true);
    expect(result.candidates).toHaveLength(0);
    expect(result.warnings.some((w) => w.includes("no observation rows"))).toBe(true);
  });
});
