/**
 * One sell allocation — shares of a specific LotOpenedEvent closed by a
 * specific SellRecordedEvent — as generated by the Allocation Engine
 * (application/services/allocationEngine.ts) by replaying explicit
 * SellAllocationDecision facts. Never persisted as user-editable state; the
 * caller's explicit decision is the raw fact, this is always its
 * deterministic replay.
 */
export interface Allocation {
  id: string;
  sellEventId: string;
  lotEventId: string;
  shares: number;
  price: number;
  fees: number;
  taxes: number;
  executionDate: string;
  executionTime?: string;
  transactionNumber?: string;
}
