/**
 * One real Buy or Sell execution, as generated by the Ledger Engine
 * (application/services/ledgerEngine.ts) from verified RawTransactions.
 * Never persisted as user-editable state — only ever the deterministic
 * output of a full regeneration, cached (ledgerCache) purely as a
 * performance materialization of that regeneration.
 */

interface LedgerEventBase {
  /** Deterministic identity for "one real execution" (ledgerRebuild.ts's canonicalKey) — regenerating from an unchanged input set always reproduces the same id. */
  eventId: string;
  executionDate: string;
  executionTime?: string;
  ticker: string;
  shares: number;
  price: number;
  fees?: number;
  taxes?: number;
  transactionNumber?: string;
  /** Every RawTransaction that corroborates this same real execution, not just whichever row survived as the canonical read. */
  sourceTransactionIds: string[];
}

export interface LotOpenedEvent extends LedgerEventBase {
  type: "LotOpened";
  companyName?: string;
}

export interface SellRecordedEvent extends LedgerEventBase {
  type: "SellRecorded";
}

export type LedgerEvent = LotOpenedEvent | SellRecordedEvent;
